# This does not support http URIs yet

assign-1-part-1: 
  uri: http://s3.amazonaws.com/saas-class/assign-1/part1_spec.rb
  type: WeightedRspecGrader
assign-1-part-2:
  uri: http://s3.amazonaws.com/saas-class/assign-1/part2_spec.rb
  type: WeightedRspecGrader
assign-1-part-3:
  uri: http://s3.amazonaws.com/saas-class/assign-1/part3_spec.rb
  type: WeightedRspecGrader
assign-1-part-4:
  uri: http://s3.amazonaws.com/saas-class/assign-1/part4_spec.rb
  type: WeightedRspecGrader
assign-1-part-5:
  uri: http://s3.amazonaws.com/saas-class/assign-1/part5_spec.rb
  type: WeightedRspecGrader

assign-2-part-1: 
  uri: http://s3.amazonaws.com/saas-class/assign-2/part1_spec.rb
  type: WeightedRspecGrader
assign-2-part-2:
  uri: http://s3.amazonaws.com/saas-class/assign-2/part2_spec.rb
  type: WeightedRspecGrader
assign-2-part-3:
  uri: http://s3.amazonaws.com/saas-class/assign-2/part3_spec.rb
  type: HerokuRspecGrader
assign-2-part-4:
  uri: http://s3.amazonaws.com/saas-class/assign-2/part4_spec.rb
  type: HerokuRspecGrader
assign-2-part-5:
  uri: http://s3.amazonaws.com/saas-class/assign-2/part5_spec.rb
  type: HerokuRspecGrader
