
  assign-0-queue:
  name: "test-pull"
  type: WeightedRspecGrader
  due : 20131118000000
  grace_period: 1
  late_period: 3
  parts:
    assign-0-part-1:
      uri: ../hw/solutions/part1_spec.rb
      type: WeightedRspecGrader
  